version: "2"

run:
  modules-download-mode: readonly
  tests: true

linters:
  enable:
    # Default linters (errcheck, govet, ineffassign, staticcheck, unused are enabled by default)
    - bodyclose     # Check if HTTP response body is closed
    - copyloopvar   # Detect loop variable issues in Go 1.22+
    - dupl          # Detect code cloning
    - errorlint     # Find code that will cause problems with error wrapping
    - exhaustive    # Check exhaustiveness of enum switch statements
    - goconst       # Find repeated strings that could be replaced by constants
    - gocritic      # Comprehensive diagnostic linter
    - gocyclo       # Detect cyclomatic complexity
    - goprintffuncname # Check that printf-like functions are named with f at the end
    - gosec         # Security-focused linter
    - misspell      # Detect commonly misspelled English words
    - noctx         # Detect sending http request without context.Context
    - predeclared   # Find code that shadows predeclared identifiers
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Detect unused function parameters
    - whitespace    # Detect leading/trailing whitespace

  disable:
    - funlen        # Too strict about function length
    - cyclop        # Redundant with gocyclo
    - lll           # Line length - let gofmt handle it
    - exhaustruct   # Too strict for struct literals
    - gochecknoinits # init functions are sometimes necessary
    - gochecknoglobals # Globals are sometimes necessary
    - paralleltest  # Not always needed

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - fmt.Fprintln
        - fmt.Fprintf

    govet:
      enable-all: true
      disable:
        - shadow          # Too strict for now
        - fieldalignment  # Struct field reordering hurts readability
        - unusedwrite     # False positives on struct fields

    gocyclo:
      min-complexity: 15

    dupl:
      threshold: 100

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    revive:
      rules:
        - name: unused-parameter
          disabled: true  # unparam handles this better
        - name: var-naming
          disabled: false
        - name: exported
          disabled: true  # Interface implementations are self-documenting

    gosec:
      excludes:
        - G204  # Subprocess with variable - needed for git/tmux execution
        - G304  # File path from variable - needed for config/plugin file reads

  exclusions:
    generated: lax
    rules:
      # Exclude some linters from running on tests
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - goconst
          - errcheck
          - gocyclo
          - funlen

      # Allow globals in main.go
      - path: cmd/tpm/main\.go
        linters:
          - gochecknoglobals

      # Allow G301 for plugin directories (0755 is standard)
      - text: "G301: Expect directory permissions to be 0750 or less"
        linters:
          - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
