version: 2

builds:
  - id: tpack
    main: ./cmd/tpack
    binary: tpack
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: tpack
    ids:
      - tpack
    name_template: "tpack_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: tmuxpack
    name: tpack

brews:
  - repository:
      owner: tmuxpack
      name: homebrew-tpack
      token: "{{ .Env.GORELEASER_TOKEN }}"
    name: tpack
    homepage: https://github.com/tmuxpack/tpack
    description: Tmux Plugin Manager
    license: MIT
    install: |
      bin.install "tpack"
    test: |
      system "#{bin}/tpack", "version"

nfpms:
  - id: tpack
    package_name: tpack
    homepage: https://github.com/tmuxpack/tpack
    description: Tmux Plugin Manager
    maintainer: tmuxpack <tmuxpack@users.noreply.github.com>
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: utils
    priority: optional
    dependencies:
      - tmux
