#!/usr/bin/env bash

# Tmux key-binding script.
# Scripts intended to be used via the command line are in `bin/` directory.

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$CURRENT_DIR/../lib/find_binary.sh"

TPACK_BIN="$(_find_tpack "$CURRENT_DIR/..")"

if [ -n "$TPACK_BIN" ]; then
	exec "$TPACK_BIN" install --tmux-echo
fi

echo "Error: tpack binary not found." >&2
exit 1
