#!/usr/bin/env bash

# Tmux key-binding script.
# Scripts intended to be used via the command line are in `bin/` directory.

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$CURRENT_DIR/../lib/find_binary.sh"

TPM_GO="$(_find_tpm_go "$CURRENT_DIR/..")"

if [ -n "$TPM_GO" ]; then
	exec "$TPM_GO" update --tmux-echo "$@"
fi

echo "Error: tpm-go binary not found." >&2
exit 1
